# Generated by Django 3.0.2 on 2020-02-16 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0002_auto_20200212_2031'),
    ]

    operations = [
        migrations.CreateModel(
            name='Running_hour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateField(default=datetime.datetime.now)),
                ('ECT', models.IntegerField(default=0)),
                ('MRT', models.IntegerField(default=0)),
                ('Machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.index')),
            ],
        ),
    ]
