# Generated by Django 3.0.2 on 2020-02-21 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_etc'),
    ]

    operations = [
        migrations.CreateModel(
            name='PmAudit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('comment', models.TextField(max_length=1000)),
                ('hour_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Running_hour')),
            ],
        ),
    ]
