# Generated by Django 3.0.2 on 2020-02-21 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0004_pmaudit'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfix',
            name='issue',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
