# Generated by Django 3.0.2 on 2020-02-22 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200221_0008'),
        ('maintenance', '0006_greasing'),
    ]

    operations = [
        migrations.CreateModel(
            name='GreaseInjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_vibrationbearing_G12', models.DateField()),
                ('Date_connectingrod_G11', models.DateField()),
                ('Date_VibRail_G10', models.DateField()),
                ('Date_Xaxis_G10', models.DateField()),
                ('Date_Yaxis_G10', models.DateField()),
                ('Date_Vcum_turbine', models.DateField()),
                ('ECT_vibrationbearing_G12', models.IntegerField(default=0)),
                ('ECT_connectingrod_G11', models.IntegerField(default=0)),
                ('ECT_VibRail_G10', models.IntegerField(default=0)),
                ('ECT_Xaxis_G10', models.IntegerField(default=0)),
                ('ECT_Yaxis_G10', models.IntegerField(default=0)),
                ('ECT_Vcum_turbine', models.IntegerField(default=0)),
                ('MRT_vibrationbearing_G12', models.IntegerField(default=0)),
                ('MRT_connectingrod_G11', models.IntegerField(default=0)),
                ('MRT_VibRail_G10', models.IntegerField(default=0)),
                ('MRT_Xaxis_G10', models.IntegerField(default=0)),
                ('MRT_Yaxis_G10', models.IntegerField(default=0)),
                ('MRT_Vcum_turbine', models.IntegerField(default=0)),
                ('index_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.index')),
            ],
        ),
    ]
