# Generated by Django 3.0.2 on 2020-02-23 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0007_greaseinjection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GreaseInjection',
        ),
    ]
