# Generated by Django 3.0.2 on 2020-02-24 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0010_injection_comment_injection_connecting_injection_vaccum_injection_vibrail_injection_xaxis_injection_'),
    ]

    operations = [
        migrations.AddField(
            model_name='injection_comment',
            name='pub_date',
            field=models.DateField(),
            preserve_default=False,
        ),
    ]
