# Generated by Django 3.0.2 on 2020-02-25 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200221_0008'),
        ('maintenance', '0014_auto_20200225_1847'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine_sharpningarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('checked_ECT', models.IntegerField(default=0)),
                ('checked_MRT', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('plate_condition', models.BooleanField(default=True)),
                ('roller_condition', models.BooleanField(default=True)),
                ('fixed_condition', models.BooleanField(default=True)),
                ('cleaning_condition', models.BooleanField(default=True)),
                ('index_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.index')),
            ],
        ),
    ]
