# Generated by Django 3.0.2 on 2020-02-25 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200221_0008'),
        ('maintenance', '0016_auto_20200225_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine_vibration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('checked_ECT', models.IntegerField(default=0)),
                ('checked_MRT', models.IntegerField(default=0)),
                ('comment', models.TextField()),
                ('vibration_moving', models.BooleanField(default=True)),
                ('vibration_vibearing', models.BooleanField(default=True)),
                ('vibration_nibearing', models.BooleanField(default=True)),
                ('vibration_belt', models.BooleanField(default=True)),
                ('vibration_Cleaning', models.BooleanField(default=True)),
                ('index_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.index')),
            ],
        ),
    ]
