# Generated by Django 3.0.2 on 2020-02-25 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200221_0008'),
        ('maintenance', '0022_routine_coda_routine_yaxis'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine_bristle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('checked_ECT', models.IntegerField(default=0)),
                ('checked_MRT', models.IntegerField(default=0)),
                ('bristle_Comment', models.TextField()),
                ('bristle_comb', models.BooleanField(default=True)),
                ('bristle_moving', models.BooleanField(default=True)),
                ('index_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.index')),
            ],
        ),
    ]
