# Generated by Django 3.0.2 on 2020-02-26 10:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0024_routine_airinlet_routine_elcabnet_routine_resultfabric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfix',
            name='hour_fk',
        ),
        migrations.AddField(
            model_name='breakfix',
            name='check_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
