# Generated by Django 3.0.2 on 2020-02-26 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0025_auto_20200226_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breakfix',
            name='check_date',
        ),
        migrations.AddField(
            model_name='breakfix',
            name='hour_fk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maintenance.Running_hour'),
            preserve_default=False,
        ),
    ]
