# Generated by Django 3.0.2 on 2020-02-26 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0029_auto_20200226_1932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etc',
            name='hour_fk',
        ),
    ]
