# Generated by Django 3.0.2 on 2020-02-26 11:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0030_remove_etc_hour_fk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pmaudit',
            name='hour_fk',
        ),
        migrations.AddField(
            model_name='pmaudit',
            name='checked_ECT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pmaudit',
            name='checked_MRT',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pmaudit',
            name='checked_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
