# Generated by Django 3.0.2 on 2020-02-27 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200221_0008'),
        ('maintenance', '0031_auto_20200226_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='breakfix',
            name='index_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.index'),
            preserve_default=False,
        ),
    ]
