# Generated by Django 3.0.2 on 2020-02-27 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20200221_0008'),
        ('maintenance', '0032_breakfix_index_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='etc',
            name='index_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.index'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pmaudit',
            name='index_fk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='index.index'),
            preserve_default=False,
        ),
    ]
