# Generated by Django 3.0.2 on 2020-02-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('site_address', models.CharField(max_length=200)),
                ('machine_type', models.CharField(max_length=100)),
                ('machine_model', models.CharField(max_length=100)),
                ('last_service', models.DateField(blank=True, null=True)),
                ('running_hour', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
