# Generated by Django 3.0.2 on 2020-02-18 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20200212_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='machine_number',
            field=models.CharField(blank=True, default='Serial_Number', max_length=100, null=True),
        ),
    ]
