# Generated by Django 3.0.2 on 2020-02-20 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_index_machine_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='index',
            name='last_service',
        ),
        migrations.RemoveField(
            model_name='index',
            name='running_ECT',
        ),
        migrations.RemoveField(
            model_name='index',
            name='running_VMT',
        ),
    ]
